#!/usr/bin/env bash

function single_domain {
	dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
	awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

function all_domain {
	domain_names=("www" "lb-01" "web-01" "web-02")

	for j in "${domain_names[@]}";
	do
		dig "${j}"."$1" | grep -A1 'ANSWER SECTION:' | \
		awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$j"
	done
}

if [ $# -lt 1 ]
then
	echo "Domain name required"
elif [ $# -eq 1 ]
then
	all_domain_details "$1";
else
	single_domain_details "$1" "$2";
fi
