#!/usr/bin/env bash
# installs and configures nginx web server to listen to port 80

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo /etc/init.d/nginx restart
