#!/usr/bin/env bash
# configure web-02 to be identical to web-01

apt-get -y update
apt-get -y install nginx

new_location='\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
error_line='\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}'

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "/server_name _;/ a \ $new_location" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/a \ $error_line" /etc/nginx/sites-enabled/default
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
